version: '2'

services:
  dynamodb:
    image: registry.gitlab.com/tokenmill/nlg/accelerated-text/dynamodb-local:latest
  s3:
    image: registry.gitlab.com/tokenmill/nlg/accelerated-text/s3-local:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
  api:
    build:
      context: ../
      dockerfile: api/Dockerfile.test
    depends_on:
      - dynamodb
      - s3
    environment:
      S3_ENDPOINT: http://s3:4572
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      AWS_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: "DEV"
      AWS_SECRET_ACCESS_KEY: "DEV"
