version: '2'

services:
  localstack:
    build:
      context: ../
      dockerfile: api/Dockerfile.localstack
    environment:
      - SERVICES=dynamodb,s3
      - DATA_DIR=/tmp/localstack/data
  api:
    build:
      context: ../
      dockerfile: api/Dockerfile.test
    depends_on:
      - localstack
    environment:
      S3_ENDPOINT: http://localstack:4572
      DYNAMODB_ENDPOINT: http://localstack:4569
      AWS_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: "DEV"
      AWS_SECRET_ACCESS_KEY: "DEV"
