AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless API - NLG

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'content-type, *'"
      AllowOrigin: "'*'"

Resources:
  generateText:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/api-1.0.0-SNAPSHOT-standalone.jar
      MemorySize: 3008
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "http://dynamodb.eu-central-1.amazonaws.com"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg
            Method: post

  deleteNLGresult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/api-1.0.0-SNAPSHOT-standalone.jar
      MemorySize: 3008
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "http://dynamodb.eu-central-1.amazonaws.com"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: delete

  getNLGresult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/api-1.0.0-SNAPSHOT-standalone.jar
      MemorySize: 3008
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: "http://dynamodb.eu-central-1.amazonaws.com"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: get

  NLGIdCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/api-1.0.0-SNAPSHOT-standalone.jar
      MemorySize: 3008
      Timeout: 60
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: options
  NLGCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/api-1.0.0-SNAPSHOT-standalone.jar
      MemorySize: 3008
      Timeout: 60
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg
            Method: options
